version: '2.1'
services:
  ###################################### PRODUCTION ####################################
  hidrofito-front:
    build:
      context: 'client'
      dockerfile: Dockerfile
      args:
        baseurl: http://200.165.138.253:8005
        port: 8081
    container_name: hidrofito-front
    ports:
      - '8081:8081' #obrigratorio
  hidrofito-back:
    build:
      context: 'backend'
      dockerfile: Dockerfile
    command: npm start
    container_name: hidrofito-back
    environment:
      NODE_ENV: production
      PORT: 8005
    tty: true
    ports:
      - '8005:8005' #obrigatorio
    network_mode: mongo_net
